import type { ReactNode } from 'react'
import { Icon } from './Icon'

export function Button({children, variant='primary', ...props}: React.ButtonHTMLAttributes<HTMLButtonElement> & {variant?:'primary'|'secondary'|'danger'|'ghost'}) {
  const styles={primary:'bg-indigo-600 text-white hover:bg-indigo-700',secondary:'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50',danger:'bg-rose-50 text-rose-700 hover:bg-rose-100',ghost:'text-slate-600 hover:bg-slate-100'}
  return <button {...props} className={`inline-flex items-center justify-center gap-2 rounded-xl px-3.5 py-2.5 text-sm font-bold transition disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${props.className||''}`}>{children}</button>
}
export function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-extrabold uppercase tracking-[0.14em] text-indigo-600">{eyebrow}</div><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div>}
export function Card({children,className='' }:{children:ReactNode;className?:string}){return <section className={`overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_18px_50px_rgba(28,36,68,.06)] ${className}`}>{children}</section>}
export function Modal({open,title,children,onClose,footer}:{open:boolean;title:string;children:ReactNode;onClose:()=>void;footer?:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-extrabold text-slate-900">{title}</h2><button onClick={onClose} className="rounded-lg bg-slate-100 p-2 text-slate-500 hover:bg-slate-200"><Icon name="X" size={16}/></button></div><div className="p-5">{children}</div>{footer&&<div className="flex justify-end gap-2 border-t border-slate-200 px-5 py-4">{footer}</div>}</div></div>}
export function Input(props: React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={`w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-500/10 ${props.className||''}`}/>}
export function Textarea(props: React.TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea {...props} className={`w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-500/10 ${props.className||''}`}/>}
export function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...props} className={`w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-500/10 ${props.className||''}`}/>}
export function Badge({children,tone='slate'}:{children:ReactNode;tone?:'green'|'amber'|'rose'|'slate'}){const c={green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',rose:'bg-rose-50 text-rose-700',slate:'bg-slate-100 text-slate-600'}[tone];return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-extrabold ${c}`}>{children}</span>}
export const statusTone=(status:string)=>status==='published'?'green':status==='review'?'amber':status==='approved'?'green':status==='rejected'?'rose':'slate'
