import { useEffect, useState, type Dispatch, type SetStateAction } from 'react'
import { api } from '../../lib/api'
import type { Category, Post, Status, Tag } from '../../types'
import { Badge, Button, Card, Input, Modal, PageHeader, Select, Textarea, statusTone } from '../../components/Ui'
import { Icon } from '../../components/Icon'

const emptyForm={title:'',excerpt:'',content:'',categoryId:'',status:'draft' as Status,tagIds:[] as number[],coverImage:''}
export default function Posts(){
 const [posts,setPosts]=useState<Post[]>([]),[cats,setCats]=useState<Category[]>([]),[tags,setTags]=useState<Tag[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState(''),[editing,setEditing]=useState<Post|null>(null),[form,setForm]=useState(emptyForm),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 async function load(){const [p,c,t]=await Promise.all([api.posts(`?q=${encodeURIComponent(q)}${status?`&status=${status}`:''}`),api.categories(),api.tags()]);setPosts(p.items);setCats(c.items);setTags(t.items)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[q,status])
 function edit(p:Post){setEditing(p);setForm({title:p.title,excerpt:p.excerpt,content:p.content||'',categoryId:String(p.category.id),status:p.status,tagIds:p.tags.map(t=>t.id),coverImage:p.coverImage||''});setError('')}
 function create(){setEditing({id:0} as Post);setForm({...emptyForm,categoryId:cats[0]?String(cats[0].id):''});setError('')}
 async function save(){setSaving(true);setError('');try{const payload={...form,categoryId:Number(form.categoryId),tagIds:form.tagIds};if(editing?.id)await api.updatePost(editing.id,payload);else await api.createPost(payload);setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setSaving(false)}}
 async function remove(id:number){if(!window.confirm('Delete this post?'))return;try{await api.deletePost(id);await load()}catch(e){setError(e instanceof Error?e.message:'Delete failed.')}}
 return <><PageHeader eyebrow="Content" title="Posts" description="Create, edit, publish and delete newsroom stories." action={<Button onClick={create}><Icon name="Plus" size={16}/> New post</Button>}/><Card><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row"><div className="relative min-w-0 flex-1"><Icon name="Search" className="absolute left-3 top-3 text-slate-400" size={16}/><Input className="pl-9" placeholder="Search title or excerpt" value={q} onChange={e=>setQ(e.target.value)}/></div><Select value={status} onChange={e=>setStatus(e.target.value)} className="sm:w-44"><option value="">All statuses</option><option value="published">Published</option><option value="review">Review</option><option value="draft">Draft</option></Select></div>{error&&<div className="m-4 rounded-xl bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700">{error}</div>}<div className="overflow-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-widest text-slate-400"><tr><th className="px-5 py-3">Post</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Author</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Views</th><th className="px-5 py-3"></th></tr></thead><tbody>{posts.map(p=><tr key={p.id} className="border-t border-slate-100 hover:bg-slate-50/60"><td className="px-5 py-4"><div className="max-w-[420px] truncate font-bold text-slate-800">{p.title}</div><div className="mt-1 text-xs text-slate-400">{new Date(p.createdAt).toLocaleDateString()}</div></td><td className="px-5 py-4"><Badge tone={statusTone(p.status) as any}>{p.status}</Badge></td><td className="px-5 py-4 text-slate-600">{p.author.displayName}</td><td className="px-5 py-4 text-slate-600">{p.category.name}</td><td className="px-5 py-4 text-slate-500">{p.views.toLocaleString()}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button variant="ghost" className="p-2" onClick={()=>edit(p)} aria-label="Edit"><Icon name="Pencil" size={15}/></Button><Button variant="danger" className="p-2" onClick={()=>remove(p.id)} aria-label="Delete"><Icon name="Trash2" size={15}/></Button></div></td></tr>)}</tbody></table>{!posts.length&&<div className="p-12 text-center text-sm text-slate-400">No posts found.</div>}</div></Card><PostModal open={!!editing} form={form} setForm={setForm} cats={cats} tags={tags} saving={saving} error={error} editing={!!editing?.id} onClose={()=>setEditing(null)} onSave={save}/></>
}
function PostModal({open,form,setForm,cats,tags,saving,error,editing,onClose,onSave}:{open:boolean;form:typeof emptyForm;setForm:Dispatch<SetStateAction<typeof emptyForm>>;cats:Category[];tags:Tag[];saving:boolean;error:string;editing:boolean;onClose:()=>void;onSave:()=>void}){return <Modal open={open} title={editing?'Edit post':'Create post'} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={saving||!form.categoryId} onClick={onSave}>{saving?'Saving...':'Save post'}</Button></>}><div className="grid gap-4"><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Headline</span><Input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Enter a strong headline"/></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Category</span><Select value={form.categoryId} onChange={e=>setForm(f=>({...f,categoryId:e.target.value}))}><option value="">Choose category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Status</span><Select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value as Status}))}><option value="published">Published</option><option value="review">Review</option><option value="draft">Draft</option></Select></label></div><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Excerpt</span><Textarea rows={3} value={form.excerpt} onChange={e=>setForm(f=>({...f,excerpt:e.target.value}))} placeholder="Short summary for listings and SEO"/></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Content</span><Textarea rows={10} value={form.content} onChange={e=>setForm(f=>({...f,content:e.target.value}))} placeholder="Write the story..."/></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Cover image URL</span><Input value={form.coverImage} onChange={e=>setForm(f=>({...f,coverImage:e.target.value}))} placeholder="https://..."/></label><div><span className="mb-2 block text-xs font-bold text-slate-600">Tags</span><div className="flex flex-wrap gap-2">{tags.map(t=><button type="button" key={t.id} onClick={()=>setForm(f=>({...f,tagIds:f.tagIds.includes(t.id)?f.tagIds.filter(id=>id!==t.id):[...f.tagIds,t.id]}))} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${form.tagIds.includes(t.id)?'border-indigo-200 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-500 hover:bg-slate-50'}`}>{t.name}</button>)}</div></div>{error&&<div className="rounded-xl bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700">{error}</div>}</div></Modal>}
